### ISSUE TITLE
New York City Police Department Midtown South Precinct Calls for Services

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#27] opened 2024-08-10 20:24 UTC
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Looking for Calls for Services in NYC, NY. 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

New York City Police Department Midtown South Precinct - NY 

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Calls for Services

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment] 2024-08-27 00:08
Duplicate of #23

**Closed** 2024-08-27 00:08 UTC
Labels: data location
