### ISSUE TITLE
New York City 88th Precinct Station Calls for Services

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#25] opened 2024-08-10 20:21 UTC
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Looking for Calls for Services in NYC, NY. 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

New York Police Department 88th Precinct Station - NY

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Calls for Services

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment] 2024-08-27 00:05
Duplicate of #23

**Closed by josh-chamberlain** 2024-08-27 00:05 UTC
Labels: data location
