### ISSUE TITLE
California police agencies public websites

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#15] opened 2024-08-10 19:14 UTC
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

We are maintaining a spreadsheet of agencies with public websites that can be scraped. We have already scraped the San Diego Police Department.

https://docs.google.com/spreadsheets/d/1f_qWiXWTcAsUNMtOQlrv0sYG4hgLfVGzupVH3Ek12Z0/edit?usp=sharing

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

California aggregated

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

We are looking to scrape records posted by California agencies under SB 1421 and SB 16, including pdfs, audio, video and other files

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment] 2024-08-27 01:53
duplicate of https://github.com/Police-Data-Accessibility-Project/scrapers/issues/206

**Closed** 2024-08-27 01:54 UTC
Labels: web scraping
